### ISSUE TITLE
Header Image Disappearance

### ISSUE THREAD

**Issue by buimwilson** [cattraken/scoulter_frameworkassignment#1]
When your page gets smaller width-wise, eventually, the gif you have next to the "TRON" name will simply disappear. Maybe this is purposeful, but I think the gif staying there, and maybe going above the "TRON" name would be cool!

**Comment by cattraken** [comment]
> When your page gets smaller width-wise, eventually, the gif you have next to the "TRON" name will simply disappear. Maybe this is purposeful, but I think the gif staying there, and maybe going above the "TRON" name would be cool!

Yeah, it's meant to be on purpose. I thought the GIF would take up too much screen space when the dimensions got smaller
